# Generated by Django 4.2.2 on 2023-10-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='ggfyfyfy', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
